apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-cm
data:
  identity.schema.json: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "name": {
              "type": "object",
              "properties": {
                "first": {
                  "title": "First Name",
                  "type": "string"
                },
                "last": {
                  "title": "Last Name",
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }
  kratos.yml: |
    version: v0.4.6-alpha.1

    dsn: memory

    serve:
      public:
        base_url: http://localhost/kratos/
        cors:
          enabled: true
      admin:
        base_url: http://kratos:4434/

    selfservice:
      default_browser_return_url: http://localhost/ui/
      whitelisted_return_urls:
        - http://localhost/ui

      methods:
        password:
          enabled: true

      flows:
        error:
          ui_url: http://localhost/ui/error

        settings:
          ui_url: http://localhost/ui/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: http://localhost/ui/recovery

        verification:
          enabled: true
          ui_url: http://localhost/ui/verify
          after:
            default_browser_return_url: http://localhost/ui/

        logout:
          after:
            default_browser_return_url: http://localhost/ui/auth/login

        login:
          ui_url: http://localhost/ui/auth/login
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: http://localhost/ui/auth/registration
          after:
            password:
              hooks:
                -
                  hook: session

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    secrets:
      cookie:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

    hashers:
      argon2:
        parallelism: 1
        memory: 128MB
        iterations: 2
        salt_length: 16
        key_length: 16

    identity:
      default_schema_url: file:///etc/config/kratos/identity.schema.json

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    
