apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kratos-selfservice-ui-node
  name: kratos-selfservice-ui-node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kratos-selfservice-ui-node
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kratos-selfservice-ui-node
      name: kratos-selfservice-ui-node
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: kratos-selfservice-ui-node-cm
          image: oryd/kratos-selfservice-ui-node:v0.6.0-alpha.2
          imagePullPolicy: IfNotPresent
          name: kratos-selfservice-ui-node
          ports:
            - containerPort: 4455
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kratos-selfservice-ui-node
  name: kratos-selfservice-ui-node
spec:
  type: ClusterIP
  ports:
    - port: 4455
      targetPort: 4455
  selector:
    io.kompose.service: kratos-selfservice-ui-node
status:
  loadBalancer: {}